---
 - name: Create tomcat directory
   file: path={{ directory }}/tomcat owner=root group=root mode=0755 state=directory
 
 - name: Install apache-tomcat-8.0.33
   copy: src={{ src }}  dest={{ dest }}

 - unarchive: src={{ dest }}/{{ tomcat_name }} dest={{ dest }} remote_src=yes setype=zip copy=no

# - name: Symlink install directory
#   file: src=tomcat/apache-tomcat-8.0.33 path=/usr/share/tomcat state=link

# - name: Change ownership of Tomcat installation
#   file: path=/usr/share/tomcat/ owner=root group=root state=directory recurse=yes

# - name: add group "tomcat"
#   group: name=tomcat

# - name: add user "tomcat"
#   user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no

 - name: Configure Tomcat server
   template: src=server.xml dest={{ tomcat }}/conf/
   notify: restart tomcat

# - name: Configure Tomcat users
#   template: src=tomcat-users.xml dest=/usr/share/tomcat/conf/
#   notify: restart tomcat

 - name:  Tomcat init script
#   template: src=/etc/ansible/roles/tomcat-standalone/files/tomcat_start.sh dest=/etc/init.d/tomcat_start mode=0755
   template: src=tomcat_start.sh dest=/etc/init.d/tomcat_start mode=0755
#   copy: src=tomcat_start.sh dest=/etc/init.d/tomcat_start mode=0755

 - name: Start Tomcat
   service: name=tomcat_start pattern=/usr/bin/java enabled=yes state=restarted

